name: release-please-main

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
      tag_name: ${{ steps.release-please.outputs.tag_name }}
      version: ${{ steps.release-please.outputs.version }}
      all: ${{ toJSON(steps.release-please.outputs) }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release-please
        with:
          command: manifest
          token: ${{ secrets.TOKEN }}
          release-type: node
          package-name: release-please-action
      - run: echo "A release was created."
          

  staging:
    runs-on: ubuntu-latest
    needs: release-please
    environment: staging
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Login to GitLab Container Registry
      run: |
          echo '${{ toJSON(needs.release-please) }}'
    - uses: docker/login-action@v2
      with:
          registry: registry.gitlab.com
          username: ${{ secrets.GITLAB_USERNAME }}
          password: ${{ secrets.GITLAB_PASSWORD }}
    - name: Build and push staging
      uses: docker/build-push-action@v4
      with:
          context: .
          file: staging.Dockerfile
          push: true
          tags: registry.gitlab.com/cyber-security-associates-ltd/starter-project/staging:${{needs.release-please.outputs.version}},registry.gitlab.com/cyber-security-associates-ltd/starter-project/staging:latest
      # - uses: actions/checkout@v3
      # - name: Build staging
        # run: |
          # echo "Building staging"
          # echo '${{ toJSON(needs.release-please) }}'

  # production:
  #   runs-on: ubuntu-latest
  #   needs: staging
  #   if: ${{ needs.release-please.outputs.release_created }}
  #   environment: production
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Build production
  #       run: |
  #         echo "Building production"

